# vim: set filetype=yaml ts=2 sw=2 sts=2 et:
#
---
name: "Build manjaro image for Hetzner cloud"

env:
  DEBUG: ${{ inputs.debug || true }}
  VERBOSE: ${{ inputs.verbose || true }}

on:
  workflow_dispatch:

  push:
    branches: [main, master]
    paths:
      - "manjaro.pkr.hcl"
      - "files/manjaro/**"

  schedule:
    # At 03:00 on Sunday - https://crontab.guru/#0_3_*_*_0
    - cron: "0 3 * * 0"

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: 3bit/setup-hcloud@v2

      - name: Build manjaro chroot sources
        run: |
          cd ./files/manjaro/sources
          [ -f manjaro.tar.gz ] || \
          docker run --privileged --tty --rm --volume $(pwd):/build -v /proc:/proc manjarolinux/base:latest bash -c 'cd /build && ./create-image.sh'

      - name: Build manjaro image for Hetzner cloud
        run: |
          IDS=( "$(hcloud image list --type=snapshot --selector="os-flavor=manjaro" --output=noheader --output="columns=id")" )

          packer build manjaro.pkr.hcl

          # delete old image(s)
          for ID in ${IDS[@]}; do
            hcloud image delete "$ID"
          done
